[package]
name = "nixc"
version = "0.0.1"
edition = "2021"

[dependencies]
cranelift = "0.104.1"
logos = "0.14.0"
miette = { version = "7.0.0", features = ["fancy"] }
rowan = "0.15.15"
thiserror = "1.0.56"
